### ISSUE TITLE
[UNTAGGED] tickets skipping some tags.

### ISSUE THREAD

**Issue by coke** [zoffixznet/perl6-buggable#1]
http://bug.perl6.party/1470328748.html

for example, shows this:

RT#124531 [UNTAGGED] Skipped tests in S03-operators/assign.t: ~< and ~> [NYI]

It's missing the [NYI] tag (presumably because it's not in first position)

**Comment by zoffixznet** [comment]
This has been resolved in R6 app whose API buggable will soon use.
