### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by AlexDaniel** [zoffixznet/perl6-buggable#15]
> \<lizmat\> AlexDaniel: why doesn't buggable generate a link like: http://modules.perl6.org/dist/Sub::Name:cpan:ELIZABETH ?

**Comment by zoffixznet** [comment]
Dunno. In that instance it would've led to a 404 anyway

**Comment by zoffixznet** [comment]
> In that instance it would've led to a 404 anyway

In those instances (so, the very first version of the dist uploaded) it'll give a CPAN url and if the dist is already on mp6o, then that URL will be given instead.
